server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#info:
#  component: DiscoveryService
#
#server:
#  port: ${port:8010}
#
#
#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone:http://${eureka.instance.hostname}:${server.port}/eureka/
#  server:
#    enable-self-preservation: false
#    waitTimeInMsWhenSyncEmpty: 0
#  instance:
#    hostname: localhost
#    lease-expiration-duration-in-seconds: 15
#    lease-renewal-interval-in-seconds: 5